---
title: "Travis Scott Burger Fantasy League"
output: github_document
knit: (function(input, ...) { rmarkdown::render(input, output_file = "README.md", envir = globalenv()) })
---

### Contents

- [Team Standings]
- [Points Scored Per Game]
- [Points Against Per Game]
- [Scatterplot of Points Scored and Against]
- [Optimal Lineup Setting]

```{r message = F, warning = F, echo = F}
library(tidyverse)
library(tvthemes)
library(googlesheets4)

theme_custom = theme_avatar() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.subtitle = element_text(hjust = 0.5, size = 9, vjust = 2.5, face = "italic"),
        plot.caption = element_text(face = "italic"),
        panel.grid.major = element_line(linewidth = 0.5, colour = "#DFDAD1"),
        panel.grid.minor = element_line(linewidth = 0.5, colour = "#DFDAD1"))

theme_set(theme_custom)
gs4_auth(email = "chadallison1251@gmail.com")
base = "https://docs.google.com/spreadsheets/"
rest = "d/1EtllzbCMieF43EHT6p0NWPj7bGglvJ-kV7q7eXtY1zA/edit?usp=sharing"
url = paste0(base, rest)
teams = read_sheet(url, sheet = 1)
games = read_sheet(url, sheet = 2)
opt = read_sheet(url, sheet = 3)

end_games = games |>
  filter(!is.na(away_score) & !is.na(home_score)) |>
  mutate(win_team = ifelse(home_score > away_score, home_team, away_team),
         win_score = ifelse(home_score > away_score, home_score, away_score),
         lose_team = ifelse(home_score > away_score, away_team, home_team),
         lose_score = ifelse(home_score > away_score, away_score, home_score))

all_teams = sort(unique(c(unique(end_games$home_team), unique(end_games$away_team))))
```

___

### Team Standings

```{r echo = F}
team_records = data.frame(team = all_teams) |>
  left_join(teams, by = c("team" = "team_name")) |>
  separate(manager, into = c("manager", "last"), sep = " ") |>
  select(team, manager) |>
  left_join(end_games |>
  count(win_team) |>
  rename(team = win_team, wins = n), by = "team") |>
  left_join(end_games |>
  count(lose_team) |>
  rename(team = lose_team, losses = n), by = "team") |>
  mutate(wins = replace_na(wins, 0),
         losses = replace_na(losses, 0),
         record = paste0(wins, "-", losses),
         pct = round(wins / (wins + losses), 3),
         team_name = paste0(team, " (", manager, ")"))

team_records |>
  ggplot(aes(reorder(team_name, pct), pct)) +
  geom_col(fill = "#90AC8D") +
  geom_text(aes(label = record), size = 3, hjust = -0.25) +
  coord_flip(ylim = c(0, max(team_records$pct * 1.05))) +
  labs(x = NULL, y = "Win Percentage",
       title = "Team Standings") +
  scale_y_continuous(breaks = seq(0, 1, by = 0.1), labels = scales::percent)
```

___

### Points Scored Per Game

```{r echo = F}
get_pts_scored = function(team) {
  home = end_games |> filter(home_team == team) |> pull(home_score)
  away = end_games |> filter(away_team == team) |> pull(away_score)
  return(mean(c(home, away)))
}

pts_scored = data.frame(team = all_teams) |>
  left_join(teams, by = c("team" = "team_name")) |>
  separate(manager, into = c("manager", "last"), sep = " ") |>
  transmute(team, team_name = paste0(team, " (", manager, ")")) |>
  mutate(scored = sapply(team, get_pts_scored))

pts_scored |>
  ggplot(aes(reorder(team_name, scored), scored)) +
  geom_col(aes(fill = scored), show.legend = F) +
  geom_text(aes(label = scored), size = 3, hjust = -0.25) +
  coord_flip(ylim = c(0, max(pts_scored$scored * 1.05))) +
  scale_fill_gradient(high = "#82B47D", low = "#CF9696") +
  scale_y_continuous(breaks = seq(0, 150, by = 10)) +
  labs(x = NULL, y = "Points Scored Per Game",
       title = "Points Scored Per Game Standings",
       subtitle = "fuck you Eric")
```

___

### Points Against Per Game

```{r echo = F}
get_pts_against = function(team) {
  home = end_games |> filter(home_team == team) |> pull(away_score)
  away = end_games |> filter(away_team == team) |> pull(home_score)
  return(mean(c(home, away)))
}

pts_against = data.frame(team = all_teams) |>
  left_join(teams, by = c("team" = "team_name")) |>
  separate(manager, into = c("manager", "last"), sep = " ") |>
  transmute(team, team_name = paste0(team, " (", manager, ")")) |>
  mutate(against = sapply(team, get_pts_against))

pts_against |>
  ggplot(aes(reorder(team_name, against), against)) +
  geom_col(aes(fill = against), show.legend = F) +
  geom_text(aes(label = against), size = 3, hjust = -0.25) +
  coord_flip(ylim = c(0, max(pts_against$against * 1.05))) +
  scale_fill_gradient(low = "#82B47D", high = "#CF9696") +
  scale_y_continuous(breaks = seq(0, 150, by = 10)) +
  labs(x = NULL, y = "Points Against Per Game",
       title = "Points Against Per Game Standings",
       subtitle = "fuck you Eric")
```

___

### Scatterplot of Points Scored and Against

```{r echo = F}
scored_against = data.frame(team = all_teams) |>
  mutate(scored = sapply(team, get_pts_scored),
         against = sapply(team, get_pts_against)) |>
  left_join(teams, by = c("team" = "team_name")) |>
  separate(manager, into = c("first", "last"), sep = " ") |>
  mutate(diff = scored - against)

scored_against |>
  ggplot(aes(scored, against)) +
  geom_point(aes(col = diff), size = 5, show.legend = F) +
  ggrepel::geom_text_repel(aes(label = first), box.padding = 0.5, segment.alpha = 0) +
  geom_hline(yintercept = mean(scored_against$against), linetype = "dashed", alpha = 0.5) +
  geom_vline(xintercept = mean(scored_against$scored), linetype = "dashed", alpha = 0.5) +
  scale_color_gradient(low = "#CF9696", high = "#82B47D") +
  scale_x_continuous(breaks = seq(0, 200, by = 5)) +
  scale_y_continuous(breaks = seq(0, 200, by = 5)) +
  labs(x = "Points Scored", y = "Points Against",
       title = "Scatterplot of Points Scored v. Against",
       subtitle = "Dashed Lines Represent League Averages")
```


<!-- NEXT: MOST POINTS SCORED IN A LOSS / FEWEST POINTS SCORED IN A WIN -->


### Optimal Lineup Setting

___

```{r message = F, warning = F, echo = F}
get_score = function(team, wk) {
  df = end_games |> filter(week == wk & (away_team == team | home_team == team))
  if (df$home_team == team) return(df$home_score)
  if (df$away_team == team) return(df$away_score)
}

get_optimal_score = function(team, wk) {
  
  df = opt |>
    filter(team_name == team & week == wk) |>
    mutate(used = 0)
  
  all_pos = unique(df$pos)
  
  for (i in 1:length(all_pos)) {
    if (!all_pos[i] %in% c("dst", "k", "qb", "rb", "te", "wr")) {
      return(warning("ensure positions entered correctly"))
    }
  }
  
  qb1 = df |>
    filter(pos == "qb" & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == qb1, 1, 0))
  
  qb2 = df |>
    filter(pos == "qb" & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == qb2, 1, 0))
  
  rb = df |>
    filter(pos == "rb" & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == rb, 1, 0))
  
  wrte = df |>
    filter(pos %in% c("wr", "te") & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == wrte, 1, 0))
  
  x1 = df |>
    filter(pos %in% c("rb", "wr", "te") & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == x1, 1, 0))
  
  x2 = df |>
    filter(pos %in% c("rb", "wr", "te") & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == x2, 1, 0))
  
  x3 = df |>
    filter(pos %in% c("rb", "wr", "te") & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == x3, 1, 0))
  
  dst = df |>
    filter(pos == "dst" & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == dst, 1, 0))
  
  k = df |>
    filter(pos == "k" & used == 0) |>
    slice_max(pts, n = 1, with_ties = F) |>
    pull(pts)
  
  df = df |>
    mutate(used = ifelse(used == 1 | pts == k, 1, 0))
  
  return(qb1 + qb2 + rb + wrte + x1 + x2 + x3 + dst + k)
  
}

teams_vec = rep(all_teams, times = max(end_games$week))
week_vec = NULL

for (i in 1:max(end_games$week)) {
  new_vec = rep(i, times = 10)
  week_vec = c(week_vec, new_vec)
}

data.frame(team = teams_vec, week = week_vec) |>
  rowwise() |>
  mutate(actual_pts = get_score(team, week),
         optimal_pts = get_optimal_score(team, week)) |>
  ungroup() |>
  mutate(missed_pts = optimal_pts - actual_pts) |>
  pivot_longer(!c(team, week, missed_pts), names_to = "class", values_to = "value") |>
  mutate(team = paste0(team, " (", round(missed_pts, 3), ")"),
         class = ifelse(class == "actual_pts", "Actual", "Optimal")) |>
  ggplot(aes(reorder(team, -missed_pts), value)) +
  geom_col(aes(fill = class), position = "dodge") +
  coord_flip() +
  labs(x = NULL, y = "Points Scored", fill = NULL,
       title = "Who sucks at setting their lineup?",
       subtitle = "Ordered top to bottom") +
  scale_fill_manual(values = c("#CF9696", "#82B47D")) +
  scale_y_continuous(breaks = seq(0, 1000, by = 10))
```















